FROM golang:1.13-alpine

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git

# Set working directory
WORKDIR /src

# Copy project to workdir
COPY . .

# Run tests
CMD CGO_ENABLED=0 go test ./... -p 1 -tags=integration